### ISSUE TITLE
Agregar combo origen de afiliación

### ISSUE THREAD

**Issue by pazarando** [PartidoDeLaRed/afiliacionespdr#4]
Necesitamos agregar un campo:
- Field Name: "source_site"
- Display Label: "Sitio de origen"
- Drop-down Options: '4mil_fundadores', 'Manual', 'Mesa'

Gracias!

**Comment by gvilarino** [comment]
Sugiero estos cambios:
- Field name -> 'source'
- 'Sitio de origen' -> 'Origen'
- '4mil_fundadores' -> '4milfundadores'

Mantengamos las cosas simples y consistentes

**Comment by pazarando** [comment]
No pudimos cambiar 'source_site'

Los otros si! Gracias!

**Comment by gvilarino** [comment]
Se los asigno a @mjlescano

**Comment by ebrenman** [comment]
listo, cambiado

e

---

Mi charla en TEDxRioDeLaPlata | El último de los Brenman 

>  https://www.youtube.com/watch?v=d5GqiVrZk1Y
